import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { Navbar } from "@/components/navbar";
import VyomaLoader from "@/components/vyoma-loader";
import { ToastProvider } from "@/components/toast-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 dark:bg-[#18181b]`} style={{fontFamily: 'Inter, ui-sans-serif, system-ui'}}>
        <ToastProvider>
            <VyomaLoader>
              <Navbar />
              <div className="max-w-5xl mx-auto px-2 sm:px-4 relative z-10 w-full">
                {children}
              </div>
            </VyomaLoader>
        </ToastProvider>
      </body>
    </html>
  );
}
